version: "3.9"
services:
  lock_manager_0:
    build:
      context: ..
      dockerfile: docker/Dockerfile.lock_manager
    env_file: ../.env
    environment:
      - PORT=8000
      - PEERS=http://lock_manager_1:8001,http://lock_manager_2:8002
    ports:
      - "8000:8000"

  lock_manager_1:
    build:
      context: ..
      dockerfile: docker/Dockerfile.lock_manager
    env_file: ../.env
    environment:
      - PORT=8001
      - PEERS=http://lock_manager_0:8000,http://lock_manager_2:8002
    ports:
      - "8001:8001"

  lock_manager_2:
    build:
      context: ..
      dockerfile: docker/Dockerfile.lock_manager
    env_file: ../.env
    environment:
      - PORT=8002
      - PEERS=http://lock_manager_0:8000,http://lock_manager_1:8001
    ports:
      - "8002:8002"
