FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY src ./src
COPY .env .env

ENV PYTHONUNBUFFERED=1
ENV PORT=8000

CMD ["sh", "-c", "python -m src.nodes.queue_node --port $PORT"]